namespace OpcUaXE.Client.Events;

/// <summary>
/// Event data for informational messages generated by the OPC UA client.
/// </summary>
public sealed class XeServiceMessageEventArgs : EventArgs
{
    /// <summary>Gets the informational message text.</summary>
    public string Message { get; }

    /// <summary>Gets the UTC timestamp when the message was generated.</summary>
    public DateTime TimestampUtc { get; }

    internal XeServiceMessageEventArgs(string message)
    {
        Message = message;
        TimestampUtc = DateTime.UtcNow;
    }

    /// <inheritdoc />
    public override string ToString() => $"[{TimestampUtc:HH:mm:ss.fff}Z] {Message}";
}
